[package]
name = "sniprun"
version = "1.3.0-beta"
authors = ["michaelb <michael.bleuez2@gmail.com>"]
rust-version="1.55"
edition = "2018"

[features]
ignore_in_ci = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
# cc="*"

[dependencies]
neovim-lib="*"
log="*"
log-panics = { version = "2", features = ["with-backtrace"]}
simple-logging="*"
close_fds="*"
thiserror="*"
dirs="*"
regex="*"
strip-ansi-escapes="*"
libc="0.2.79"
serial_test = "*"

# jupyter-client = { git = "https://gitlab.com/srwalker101/rust-jupyter-client.git", branch = "dev" }


# Python3 interpreter
unindent="*"
