on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always


jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --release --verbose
    - run: mv ./target/release/sniprun .

    - uses: johnwbyrd/update-release@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      asset: ./sniprun
      message: "Binary automatically published by github actions"
      draft: true
