name: Rust

on:
  push:
    branches: [ master, dev]
  pull_request:
    branches: [ master, dev]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name : build

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release

  buildnightly:
    name: build-nightly
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: build
        run: cargo build --release

  unittest:
    name: unit tests
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - run: './ressources/install_all_compilers_ci.sh'

    - uses: dlang-community/setup-dlang@v1



    - name: Unit tests
      run: cargo test --features ignore_in_ci

    - name: Integration tests
      run: cargo test --features ignore_in_ci --test integration




  install:
    name: install (download)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Installation tests
      run: ./install.sh


 

  codecov:
    name : codecov
    runs-on: ubuntu-20.04
    steps:
    - name : allow add cargo to path
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v2

    - run : './ressources/install_all_compilers_ci.sh'

    - uses: dlang-community/setup-dlang@v1

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true


    - run: rm -rf ./target *.prof*
    - run: export RUSTFLAGS="-Zinstrument-coverage" 
    - run: export LLVM_PROFILE_FILE="sniprunlcov-%p-%m.profraw" 
    - run: cargo install grcov
    - run: rustup component add llvm-tools-preview


   

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test --features ignore_in_ci --exclude-files src/interpreters/example.rs && cargo test --test integration

    - name: Generate report
      run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing -o ./lcov.info 

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
          token: ${{secrets.CODECOV_TOKEN}}


